language: node_js
node_js:
 - '4'
 - '6'
 - '8'
 - '9'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: required
before_install:
 - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
